blueprint:
  name: TRV Sync
  description: Sync TRV  
  domain: automation
  input:
    trv_source:
      name: Source TRV
      selector:
        entity:
          domain: climate
    trv_destination:
      name: Destination TRV
      selector:
        entity:
          domain: climate

mode: restart

variables:
  

  target_temp: '{{ state_attr(trv_source, "temperature") }}'
  target_temp_state: '{{ states(trv_source, "temperature") }}'
  
  trv_mode: '{{ states(trv_source) }}'
  
  
trigger:
  - platform: state
    entity_id: !input trv_source
    for:
      hours: 0
      minutes: 0
      seconds: 0

  - platform: state
    entity_id: !input target_temp
    for:
      hours: 0
      minutes: 0
      seconds: 0

condition:
 
  - condition: template
    value_template: '{{ target_temp_state != "unavailable" and target_temp_state != "unknown" }}'
  - condition: template
    value_template: '{{ trv_mode != "unavailable" and trv_mode != "unknown" }}'
 
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: climate.set_temperature
    target:
      entity_id: !input trv_destination
    data:
      data:
        temperature: !input target_temp
        hvac_mode: !input trv_mode
        
