blueprint:
  name: TRV Calibrator
  description: Calibrate your TRV using an external sensor
  domain: automation
  input:
    trv:
      name: Smart TRV
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Temperature Sensor
      description: Sensor used to calibrate your TRV
      selector:
        entity:
          domain: sensor
          device_class: temperature
    trv_calibration_number:
      name: TRV Calibration State
      selector:
        entity:
          domain: number
          device_class: temperature
    trv_calibration_number_step_override:
      name: TRV Calibration State Step Override (Optional)
      description: Sometimes the TRV support a different precision than a supported one. Check state attributes in Developer Tools.
      default: 0
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
          unit_of_measurement: °C

mode: restart

variables:
  trv: !input trv
  trv_calibration_number: !input trv_calibration_number
  trv_calibration_number_step_override: !input trv_calibration_number_step_override
  temperature_sensor: !input temperature_sensor

  trv_state: '{{ states(trv) }}'
  trv_calibration_number_state: '{{ states(trv_calibration_number) }}'
  temperature_sensor_state: '{{ states(temperature_sensor) }}'

  trv_calibration_step: >- 
                        {% if trv_calibration_number_step_override == 0 %}
                          {{ state_attr(trv_calibration_number, "step") | float(1) }}
                        {%- else -%}
                          {{ trv_calibration_number_step_override }}
                        {%- endif %}
  trv_calibration_step_decimals: >- 
                                {% set step = trv_calibration_step | string %}
                                {% if step.split(".") | length > 1 -%}
                                  {{ step.split(".")[1] | length }}
                                {%- else -%}
                                  {{ 0 }}
                                {%- endif %}
  room_temperature: '{{ temperature_sensor_state | float(0) }}'
  trv_temperature: '{{ state_attr(trv, "current_temperature") | float(0) }}'
  trv_calibration: '{{ trv_calibration_number_state | float(0) }}'
  trv_calibration_min: '{{ state_attr(trv_calibration_number, "min") | float(-5) }}'
  trv_calibration_max: '{{ state_attr(trv_calibration_number, "max") | float(5) }}'
  new_trv_calibration: '{{ room_temperature - trv_temperature + trv_calibration }}'
  new_trv_calibration_bounded: '{{ [ [ (new_trv_calibration - new_trv_calibration % trv_calibration_step) | round(trv_calibration_step_decimals), trv_calibration_min ] | max, trv_calibration_max ] | min }}'

trigger:
  - platform: state
    entity_id: !input trv
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id: !input trv_calibration_number
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id: !input temperature_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0

condition:
  - condition: template
    value_template: '{{ trv_state != "unavailable" }}'
  - condition: template
    value_template: '{{ trv_calibration_number_state != "unavailable" }}'
  - condition: template
    value_template: '{{ temperature_sensor_state != "unavailable" }}'
  - condition: template
    value_template: '{{ trv_calibration < new_trv_calibration_bounded - trv_calibration_step_decimals or new_trv_calibration_bounded + trv_calibration_step_decimals < trv_calibration}}'


action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: number.set_value
    target:
      entity_id: !input trv_calibration_number
    data:
      value: '{{ new_trv_calibration_bounded }}'
